### ISSUE TITLE
Make starting a time entry happen in a single transaction

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#109]
## Description
For quick prototyping purposes, we made starting/stopping something that happens in the repository layer. It should instead be made in a single [`@Transaction`](https://developer.android.com/reference/android/arch/persistence/room/Transaction) in the DAO layer.

## Definition of done
- [ ] The TimeEntryDAO has a stop method that queries the DB and stops a running entry, if any
- [ ] The TimeEntryDAO has a start method that, in a single transaction, calls the method to stop the running TE and then create the new time entry.

**Comment by daividssilverio** [comment]
As commented here https://github.com/toggl/android/pull/105#discussion_r402321387
Our repository is currently using multiple calls to the `TimeEntryDao` to execute operations that could've been done with a single statement.

In the `Repository`:
- `stopRunningTimeEntry` calls to `getAllRunningTimeEntries`, then makes another call to `updateAllTimeEntries` to update the duration of affected time entries. This could be replaced with a single sql statement (we just gotta figure out the duration situation and why we are trying to update multiple time entries).
- `startTimeEntry` makes a call to `stopRunningTimeEntry` and the creates another time entry. This one in particular could be put inside a transaction inside the `TimeEntryDao` if we manage to create the `stopRunningTimeEntry` update statement.

**Comment by semanticer** [comment]
Unfortunately, I don't think we can make`stopRunningTimeEntry` use only one single database query. We can do this:
```kotlin
@Query("UPDATE time_entries SET duration = (:now - startTime) WHERE duration is null")
fun stopRunningTimeEntries(now: OffsetDateTime): Int
```
The problem is that we need to return `TimeEntry?` from `stopRunningTimeEntry` but there is no way to get back TimeEntries that were updated. The only info we can get is the number of updated items as `Int`.
