### ISSUE TITLE
Create Suggestion models

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#14]
## Description
We need to create the suggestion model. It should copy the implementation that currently exists in the Xamarin app. We also need to add a case to the `TimeEntryViewModel` discriminated union that represents a suggestion (it can be a simple wrapper).

## Definition of done
- [ ] The suggestion type is created
- [ ] The `TimerState.LocalState` type should have a property to hold the list of suggestions
- [ ] These properties get mapped to `TimeEntriesLogState`
- [ ] When performing the mapping from `List<TimeEntry>` into a `List<TimeEntryViewModel>`, we should add the suggestions at the top
- [ ] We should add unit tests to check that the mapping function is behaving accordingly (specially since it will grow a lot once we start adding grouping behavior)

**Comment by semanticer** [comment]
@heytherewill `Suggestion` from our Xamarin app is already a highly redundant fattened model for UI usage with properties like `ProjectColor`, `ProjectName` as well as `ProjectId`. 
I'm not 100% sure how we want to implement our `Suggestion` in the model module. I see a couple of different options:

1) Not sure if we want to persist suggestions (probably not) but we could still treat `Suggestion` model as other db entity models. Therefore we would include `projectId` as a "foreign-key" but no projectName properties etc. We also need to think about how to represent tasks.
2) Do a proper UI model with `project` and `task` already nested inside for easy UI use. This model would be probably mapped from other models on the repository layer maybe also with some use of lower-level model from solution numero uno 👆
3) The same thing we do in Xamarin app but it looks ugly to me

This all depends on how suggestions will be implemented and you know probably much more about that than I do.

I guess a more fundamental question is what kind/kinds of models do we want in **model** module.
