### ISSUE TITLE
Investigate and upgrade our tests to use Kotest 4.0

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#151]
## Description
Currently, our tests are slow to write/change because. IDE auto completion is very sluggish and not dev friendly. 
The idea is that maybe kotest 4.0 is faster.

## Dependencies
None.

## Definition of done
- [ ] Kotest is migrated to 4.0
- [ ] Tests are migrated to 4.0 (if needed)
- [ ] Auto completion is faster on test files

**Comment by heytherewill** [comment]
If Kotest 4.0 is not faster, we should just switch to jUnit since it also unblocks #144

**Comment by daividssilverio** [comment]
Well, besides being able to find the tests in the [upgrade branch: kotest4](https://github.com/toggl/android/tree/kotest4) (at least from the IDE).

I didn't perceive any performance gain from the IDE when writing tests.

But, I've noticed that this might just be a problem on AndroidStudio, the kotlin compiler or something else, and not the tests themselves that are slow.
If we break the tests down into smaller test classes, creating smaller test lambdas, the IDE does it job faster and the syntax highlight is more tolerable.

**Comment by heytherewill** [comment]
Closing as will not fix
