### ISSUE TITLE
Set up app flavors

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#16]
## Description
Let's configure the build system so that installing a Debug, AdHoc and release builds yield different app ids so that we can have different installed apps on our phones. *NOTE: For now, let's stick to using `com.toggl` as the base bundle ID*

## Definition of done
- [x] The app name is changed to Aurora (we will revert that once we are ready to ship)
- [x] The app icons is set to be the same as the one from the Xamarin app
- [x] The Debug AdHoc and Release builds of the app have different icons 
- [x] The Debug AdHoc and Release builds can co-exist in our phones
- [x] The debug bundle id should be `{base bundle Id}.debug`
- [x] The AdHoc bundle id should be `{base bundle Id}.adhoc`

**Comment by semanticer** [comment]
@heytherewill There are a few things we need to clarify. There are two different dimensions on which you can define your **build variant**. **Flavors** and **build types** and the combination of these two forms **build variant**. 
I think you are actually talking about different build types, not flavors. I would use flavors for example to distinguish **mock**, **staging** and **prod** environments, do we want to set up these now btw?
Also one more question - what exactly do we mean by AdHoc - how is it different from debug and release?
