### ISSUE TITLE
Figure out animations/transitions for The Wheel ™

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#164]
## Description
This issue is here to make sure we consider animations/transitions for The Wheel ™️.
At a minimum, we consider the guidelines at https://material.io/design/motion/#principles.
Ideally, we discuss this together with our designers and figure out delightful interactions.

## Definition of done
- [x] We have a list of animations we are gonna implement or simply spec; or decide that we don't need anything special
- [x] We have a list of transitions we are gonna implement or simply spec; or decide that we don't need anything special
- [ ] The documentation is updated to reflect the changes done in this PR (Gotta document whatever we decide here, possibly sharing ideas with the iOS version)

**Comment by AlicjaSuska** [comment]
@daividssilverio here you mean:
1. animations directly on the wheel or
2. how it appears on the screen?

If 1 - we already have them in the apps, I think we can continue with that
if 2 - I've desribed it in add/edit TE animations issue

Please, let me know if I'm missing something

**Comment by daividssilverio** [comment]
@AlicjaSuska 

I meant both.
For 2. we are good then, ref: https://github.com/toggl/android/issues/163#issuecomment-613286716

Some ideas: 
- Provide some entry animation for the wheel, making the handles spin in place when opening the wheel for an existing time entry (might be annoying).
- Animate the handles when changing time manually using the date/time pickers.

Plus having what we already have of course: haptic feedback when using the start/end handles.

**Comment by daividssilverio** [comment]
Alright, lets get some specs o/

As we [discussed internally](https://toggl.slack.com/archives/CS25QL11P/p1586979434007800), the wheel and the edit duration don't have a small view anymore. Being part of the expanded StartEdit view only.

@AlicjaSuska 
- what do you think about my ideas on the [comment above](https://github.com/toggl/android/issues/164#issuecomment-613715145)?
- Other than that, I think that all we need to do is to smoothly auto scroll to focus on the EditDuration view when the user clicks on the "clock" or the "duration label" in the [collapsed StartEdit view](https://toggl.invisionapp.com/d/main#/console/19556473/409562661/preview). What do you think?

**Comment by AlicjaSuska** [comment]
@daividssilverio agree with you on almost everything. the only issue are the spinning handles. How about we just make them 'pop' slightly - make them 4px smaller, than bigger

**Comment by daividssilverio** [comment]
Hey @AlicjaSuska

Nice, then I'll be creating issues for my ideas and yours.
Let me just be clarify, what you are suggesting is an animation when the user first taps the spinning handles, right? something to pass along the idea of the handle being pressed?

**Comment by AlicjaSuska** [comment]
yes, that's what I mean. Thank you @daividssilverio :)

**Comment by daividssilverio** [comment]
List of issues for the Wheel's animations/transitions:
- [ ] [Animate the start/end handles when changing time outside of the wheel](https://github.com/toggl/android/issues/288)
- [ ] [Improve the touch & feel of the wheel's spinning handles](https://github.com/toggl/android/issues/289)
- [ ] [Provide some entry animation for the wheel, making the handles spin in place when opening the wheel for an existing time entry](https://github.com/toggl/android/issues/290)

➿@heytherewill

**Comment by heytherewill** [comment]
Can this one be closed as well, @daividssilverio?

**Comment by daividssilverio** [comment]
Yeah, I think we won't have much more added to these specs, at least for now.
