### ISSUE TITLE
Add the ViewModel that represents the time entries log header

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#20]
## Description
We need to add another case to the `TimeEntryViewModel`, one that represents the headers that group each day. The class should contain a string that is the representation of the current day and a `Long` that is the total duration of all time entries in that day.

## Dependencies
Depends on #19 because we want that date time goodness.

## Definition of done
- [ ] The entity is added as part of the discriminated union that represents the possible states of the `TimeEntryViewModel`.

**Comment by semanticer** [comment]
Not sure why is this dependent on #19

**Comment by heytherewill** [comment]
Because of the time classes that will be added there

**Comment by heytherewill** [comment]
Because of the time classes that will be added there

**Comment by heytherewill** [comment]
Because of the time classes that will be added there
