### ISSUE TITLE
Double and not descriptive option "Running timer" in settings

### ISSUE THREAD

**Issue by Rabattkarte** [toggl/android#22]
## Description

There's a double option "Running timer" within settings under "TIMER DEFAULTS" with no description at all. Please see attached screenshot. 

Basically it's two problems:

0. There should just be one option, not two. Or it's a typo?
1. I'm not sure what the setting is. Maybe add a descriptive text?

Some more infos:

- Toggl app version is: `2.11.1 (52110102)`
- Android version 9
- OxygenOS version: 9.0.6
- Device: OnePlus 3 (ONEPLUS A3003)

## Dependencies

None, I guess.

## Definition of done

Have only one option or maybe fix the option name if it's a typo.

**Comment by daividssilverio** [comment]
Fixed on https://github.com/toggl/mobileapp/pull/7119
