### ISSUE TITLE
🚧Refactor Main Log using Epoxy library

### ISSUE THREAD

**Issue by semanticer** [toggl/android#224]
## Description
We will refactor the Main Log recycler view using [Epoxy](https://github.com/airbnb/epoxy). During this process, we should set up the basic infrastructure for possible future Epoxy usage. We should be able to do this with minimal layout changes and re-use most of our [ViewHolder code](https://github.com/airbnb/epoxy/wiki/ViewHolder-Models).

## Dependencies
None

## Definition of done
- [ ] We have the infrastructure for Epoxy and it's further usage ready
- [ ] Main log is refactored using epoxy with re-used [ViewHolder code](https://github.com/airbnb/epoxy/wiki/ViewHolder-Models)
- [ ] Swipe actions are refactored to use https://github.com/airbnb/epoxy/wiki/Touch-Support
- [ ] Old adapter is removed

**Comment by heytherewill** [comment]
Do note that this is an investigation issue; if the end result bloats the APK and does not add much legibility, it should not be merged :)

**Comment by heytherewill** [comment]
Removing this from milestones for the time being :respect-f:

**Comment by heytherewill** [comment]
Now that we are using compose, does this even matter?

**Comment by semanticer** [comment]
No
