### ISSUE TITLE
Crash when resuming the activity with edit dialog fragment open

### ISSUE THREAD

**Issue by pdrj** [toggl/android#227]
## Description
When the start/edit dialog is open **and don't keep activities option is active**, we get a crash when resuming the app. It triggers this exception:
```
            is StartEditAction.DescriptionEntered ->
                state.mutateWithoutEffects {
                    editableTimeEntry ?: throw EditableTimeEntryShouldNotBeNullException()
```
from `StartEditReducer`. 

What I suppose is happening is that Android wants to restore the fragment's state for us, thus re-entering text into the description field. Since there's no `EditableTimeEntry` in state - we get a crash.

## Definition of done

- [ ] Coming back to the activity [in a scenario described above] results in no crash

**Comment by semanticer** [comment]
It's not crashing for me, however, the state is not re-emitted therefore the view is not repopulated:

 ![restorefail](https://user-images.githubusercontent.com/535613/84501598-0de00800-acb7-11ea-89e8-79a0f2082568.png)

**Comment by semanticer** [comment]
I've created a new issue for this https://github.com/toggl/android/issues/458 
@pdrj if you can re-test this and close this issue in case it no-longer crashes for you
