### ISSUE TITLE
Investigate scrolling behavior on large screens

### ISSUE THREAD

**Issue by pdrj** [toggl/android#236]
## Description
@heytherewill noticed some scrolling weirdness in our start/edit fragment when it's not fully expanded. That might be due to the nested scroll view. 

## Definition of done

- [ ] using a large screen, validate that scrolling works as it should and no weird interactions happen in the start/edit fragment
- [ ] if some weirdness is noticed, it is fixed (maybe we'll have to disable nested scrolling when the  view is compacted, for instance)

**Comment by heytherewill** [comment]
This was also closed by #471
