### ISSUE TITLE
In the Small Add Project view, the color picker should appear from the bottom of the screen

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#250]
## Description
This issue is here to ensure that the small color picker view appears from the bottom of the screen when creating a project from the "Small Add Project" view.

## Dependencies
Another early issue, but the "Add project view" has to be implemented.
This issue can be closed alongside the issue that will handle displaying the "Small Project Color Picker" view.
Check the [designs for reference](https://toggl.invisionapp.com/d/main#/console/19556473/410585734/preview).

## Definition of done
- [ ] The small color picker view slides up/down smoothly into/out of the small add project view.

**Comment by heytherewill** [comment]
New designs rendered this issue obsolete
