### ISSUE TITLE
Update the StartEditReducer's AutocompleteSuggestionTapped action to handle create project suggestions

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#255]
## Description
When you select a create project suggestion, it sets the editableProject property and that opens the project creation popup

## Definition of done
- [ ] The project creation sheet appears when the project created autocomplete suggestion is tapped
- [ ] Tests ensure that the behavior is correct
- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
🤔 I just noticed that we didn't handle the token description truncation that should happen when you tap a Create project suggestion 🤔 @heytherewill
