### ISSUE TITLE
Update the StartEditReducer's AutocompleteSuggestionTapped action to handle TimeEntry suggestions

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#258]
## Description
When the user picks a suggested a time entry, we change the details of the entry being edited/created to match the selected suggestion
Bear in mind that this method should never alter the id(s) of the running time entry, just all all other fields
## Definition of done
- [ ] Tests ensure that the behavior is correct
- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
🤔 not all other fields right? `startTime` and `duration` shouldn't be copied as well, right? @heytherewill
