### ISSUE TITLE
Update the StartEditReducer's AutocompleteSuggestionTapped action to handle tag creation suggestions

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#260]
## Description
When you select a create tag suggestion, it returns an effect that creates a new tag. This effect should then emit a TagCreated action which handles adding the tag to the editable TE.
Selecting a tag creation suggestion should also remove the word that starts with a # from the description (do so by checking the cursor position as well)

## Dependencies
Depends on #252

## Definition of done
- [ ] Tests ensure that the behavior is correct
- [ ] The documentation is updated to reflect the changes done in this PR

- Tag suggestions add the tag to the list of tags of the editable time entry 
- Create tag suggestions create a new tag using an effect. This effect should then emit a TagCreated action which handles adding the tag to the editable TE

**Comment by daividssilverio** [comment]
It seems like there's some ©️ 🍝 leftovers on the description here.

> If the project is in a workspace different than the one of the time entry, the time entry workspace is changed as well

This ☝️ doesn't apply to this issue, right? Also
> Selecting a project suggestion should also remove the word that starts with an @ from the description (do so by checking the cursor position as well)

should be:
Selecting a create tag suggestion should also remove the words that starts with an # from the description.

**Comment by heytherewill** [comment]
Updated 👌
