### ISSUE TITLE
Display the list of autocomplete suggestions in the start edit view

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#262]
## Description
We need to react to the list of autocomplete suggestions and display it according to the designs in Invision
Tapping any of the items in that list should dispatch an AutocompleteSuggestionTapped action

## Definition of done
- [ ] The list is displayed in the UI
- [ ] Tapping items in the list dispatch actions accordingly
- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
Putting this on hold until we reach a decision about how we're gonna implement the suggestions ([popup only] vs [popup on expanded view & back list view that appears on small view])

Discussions running here: https://toggl.slack.com/archives/C02APMYTM/p1589843352018800 and https://toggl.slack.com/archives/CUHSVKLUV/p1589875295096000
