### ISSUE TITLE
 Add the ItemTapped action

### ISSUE THREAD

**Issue by juanlaube** [toggl/android#270]
## Description

Add the ItemTapped action and handle it in the reducer. This should simply set the selected item in the state.

## Definition of done
- [ ] The `selectedItem` is set in the state with an editable time entry
- [ ] Tests are created

**Comment by semanticer** [comment]
@juanlaube According to our documentation `ItemTapped` has `CalendarItem` object as a parameter. Should I create `CalendarItem` as part of this issue?
