### ISSUE TITLE
In the Expanded Add Project view, the color picker should slide in to appear on screen

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#286]
## Description
This issue is here to ensure that the color picker view fades in/out and slides down/up when creating a project from the "Expanded Add Project" view.

## Dependencies
Another early issue, but the "Add project view" has to be implemented.
This issue can be closed alongside the issue that will handle displaying the "Project Color Picker" view.
Check the [designs for reference](https://toggl.invisionapp.com/d/main#/console/19556473/412698550/preview).

## Definition of done
- [ ] The color picker view fades in/out and slides up/down smoothly into/out in the expanded add project view when clicking the project color indicator.

**Comment by heytherewill** [comment]
Outdated
