### ISSUE TITLE
Include the selected item in the calendar items selector

### ISSUE THREAD

**Issue by juanlaube** [toggl/android#328]
## Description
We need to include the selected item in the calendar items selector.
To consider this case, add a new data class `EditableTimeEntry` to `CalendarItem` and replace the time entry that matches the editable time entry in the state, or append the editable time entry at the end in case it's a time entry without an id yet.

## Definition of done
- [x] The EditableTimeEntry data class is added to the CalendarItem
- [x] The selectedItem is passed to the selector
- [x] When it's an editable time entry with an id, replace the the matching time entry with it
- [x] When it's an editable time entry without an id, append the editable time entry case in the end
- [x] Tests are added for cases with an editable time entry with and without an id

**Comment by daividssilverio** [comment]
Closed via #420
