### ISSUE TITLE
Reducer decorators

### ISSUE THREAD

**Issue by semanticer** [toggl/android#330]
## Description
Add a way to decorate reducers with another reducer so they gain their behavior. Base reducers should include the needed state and an action to redirect decorator actions.

## Definition of done
- [ ] Add instance method on reducer to decorate them
- [ ] Create core time entries reducer
- [ ] Decorate all reducers that handle time entries with the time entries reducer
- [ ] Write tests for time entry reducer
- [ ] Fix and update all old tests
- [ ] Edit documentation

**Comment by heytherewill** [comment]
Also: Please update the documentation to update the time entry handling actions in the docs and include the time entries reducer

**Comment by semanticer** [comment]
I'm changing the size estimate of this Issue to **L** I think we underestimated the number of changes in our test code. We also decided to change slightly all of our TE effects and repository methods(DTO usage etc). 

The PR is not finished yet and it's already bigger than the iOS equivalent.
