### ISSUE TITLE
Implement dark mode project colour transforms

### ISSUE THREAD

**Issue by dshr** [toggl/android#351]
## 🎯 What needs to be done
To help visibility in dark mode we're going to apply a transform to our project colours. Using the HSB interface from #349 change the outputted project colour using this formula:

```
H_dark = H
S_dark = S*B/100
B_dark = (200+B)/3
```

Depends on #349

**Comment by heytherewill** [comment]
This function is a size-s, really, since we have the implementation done in Xamarin and we just need to copy it
