### ISSUE TITLE
Create the default colour selection view

### ISSUE THREAD

**Issue by dshr** [toggl/android#379]
## Description
Implement the view and connect it to the state. Designs are here: https://toggl.invisionapp.com/d/main#/console/20014282/419193922/preview

## Dependencies
Depends on #348, #344, #351 and #378

## Definition of done
- [x] The default colour and custom colour views are defined
- [x] The default colour transforms the project colour depending on light/dark mode, based on code from #299
- [ ] The custom colour view can have an optional lock overlay, which is always visible for now.
- [ ] The actual view is implemented in IB (I suggest two UIStackViews)
- [ ] The view appears when the `colorPickerMode` flag is set to `.openFree`
- [ ] The view is populated with the default colours + the custom colour placeholder
- [ ] The view gets the project colour from the state and highlights the appropriate option
- [ ] Tapping on a default colour emits a `.colorPicked` action
- [ ] Tapping on the custom colour placeholder does nothing
- [ ] Tapping on the close button emits a `.closeColorPicker` action

**Comment by heytherewill** [comment]
For Android, this is a lot simpler using a RecyclerView rather than having 15 views

**Comment by heytherewill** [comment]
Also, the referenced issue is wrong, likely a ©️ 🍝 from iOS
