### ISSUE TITLE
Add suggestions boilerplate code

### ISSUE THREAD

**Issue by sofokli1** [toggl/android#385]
## Description
Add suggestions boilerplate code
## Dependencies
None
## Definition of done
- [x] Create empty feature with all required files
- [x] Hook everything to the main feature
- [x] Combine the [SuggestionProviderType](https://github.com/toggl/mobileapp/blob/develop/Toggl.Core/Suggestions/SuggestionProviderType.cs) and the [Suggestion](https://github.com/toggl/mobileapp/blob/develop/Toggl.Core/Suggestions/Suggestion.cs) Model into 1 enum with associated values like:
```swift
enum Suggestion {
    case mostUsed(description: String, color: String, ...etc) 
    case calendar(...) }
```
- [ ] Inject the following dependencies in the reducer:
Calendar service (mock if not available)
Repository
Analytics service (mock if not available)
Time service

**Comment by heytherewill** [comment]
What do we need the analytics service for? Analytics should be handed by the AnalyticsReducer instead

**Comment by sofokli1** [comment]
will reevaluate your comment next week

**Comment by sofokli1** [comment]
good point about the analytics. will update the issues
