### ISSUE TITLE
Ensure that all actions have tests

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#40]
## Description
Some actions (namely the ones added during the prototype phase) don't have proper tests associated to them. Let's fix this.

## Definition of done
- [x] All actions related to the `TimeEntriesLog` feature should have tests
- [ ] All actions related to the `StartTimeEntry` feature should have tests

**Comment by semanticer** [comment]
There are too many things clashing with https://github.com/toggl/android/pull/43 I will wait for that PR to finish and then add some ✨on top of it
