### ISSUE TITLE
Display the project name properly when tapping a CreateProject suggestion

### ISSUE THREAD

**Issue by daividssilverio** [toggl/android#408]
## Description
I didn't go through the investigation on what's causing this, but the current behaviour is happening:

When `AutocompleteSuggestion.CreateProject` is fired and the `Project` view appears, we have two problems:
1. The name of the suggestion isn't filled in the description field
2. If you type anything in the description field, another `Project` view appears on top of the existing one.

## Dependencies
Depends on #335

## Definition of done
- [ ] When the `AutocompleteSuggestion.CreateProject` is tapped, a project view appears pre-filled with the suggestion's name.
- [ ] Changing the description in the project dialog shouldn't pop new `Project` views.

**Comment by heytherewill** [comment]
Fixed by #412
