### ISSUE TITLE
Hide the keyboard when selecting project colours

### ISSUE THREAD

**Issue by dshr** [toggl/android#432]
## Description
Unfocus the project name input whenever the colour selection button is tapped. 

## Definition of done
- [ ] The project view is positioned appropriately when the keyboard is visible, hiding the colour UI
- [ ] The project view is positioned appropriately when the keyboard is hidden, showing the colour UI fully
    - [ ] The view slides up and down when needed
- [ ] UI changes are animated appropriately

**Comment by heytherewill** [comment]
This was closed by #412
