### ISSUE TITLE
Add SmartAlertsAllowAccessTapped action

### ISSUE THREAD

**Issue by sofokli1** [toggl/android#451]
## Description
Add `SmartAlertsAllowAccessTapped` action. It should update the `UserPrefs` object in the state. Add the missing property if needed.

Also add the `RequestNotificationPermission` effect and `NotificationPermissionReceived` action

Check [notion](https://www.notion.so/toggl/Settings) for details regarding parameters and effects

## Dependencies
#435
## Definition of done
- [ ] Add SmartAlertsAllowAccessTapped action
- [ ] Add RequestNotificationPermission effect
- [ ] Add NotificationPermissionReceived action
- [ ] Add tests

**Comment by daividssilverio** [comment]
We don't need the `RequestNotificationPermission` and `NotificationPermissionReceived` action on android.
Android doesn't need the user permission to show notifications. I think we can have the complexity of this issue reduced to `size-S`.

The users have total control over their notification channels. Although we currently don't do anything about it, we could in theory add something to the UI to let the users know that their notification channels are disabled and direct them to the settings if necessary.

**Comment by semanticer** [comment]
Here is how I understand Smart alert logic on android:
You enter smart alert settings screen via `SettingTapped(SmartAlert)` and then you simply select one of the options(including disabled option) using `SmartAlertsOptionSelected(SmartAlertsOption)` and that should be everything we need as far as I understand this.

Therefore I think this whole issue is unnecessary right @sofokli1 ?

**Comment by sofokli1** [comment]
@semanticer If you do not need to request permissions for notifications, I agree with you.

**Comment by semanticer** [comment]
Closing this issue as it is unnecesssary on Android.

**Comment by semanticer** [comment]
Closing this issue as it is unnecessary on Android.
