### ISSUE TITLE
Add SmartAlertsOpenSettingsAppTapped action

### ISSUE THREAD

**Issue by sofokli1** [toggl/android#452]
## Description
Add `SmartAlertsOpenSettingsAppTapped' action. It should take the user to the settings app as the old app (or whatever the platform usually does in this case)

Check [notion](https://www.notion.so/toggl/Settings) for details regarding parameters and effects

## Dependencies
#435
## Definition of done
- [ ] Add SmartAlertsOpenSettingsAppTapped action
- [ ] Add tests

**Comment by daividssilverio** [comment]
This issue currently does not apply to android. We don't have anything in the UI that leads to the notifications's settings app.
We could provide something. I'll ping the designers about it and we can re-open this issue if necessary.
