### ISSUE TITLE
Add the DatePicker module

### ISSUE THREAD

**Issue by juanlaube** [toggl/android#480]
## Description 
Add the boilerplate for the date picker module in the calendar feature.

## Definition of done
- [x] The DatePickerFeature is added
- [ ] The DatePickerCoordinator is added
- [x] The DatePickerAction is added
- [x] The DatePickerReducer is added
- [x] The DatePickerState is added
- [ ] The DatePickerSelector is added

**Comment by daividssilverio** [comment]
This has already been done on #331

**Comment by daividssilverio** [comment]
Oops... only the modules have been added.
