### ISSUE TITLE
Settings: Add settings view

### ISSUE THREAD

**Issue by sofokli1** [toggl/android#512]
## Description
- Adds the settings button to the calendar and log view (check designs). 
- Decide on how to better construct the view (ideally take inspiration from the modular way it was done in the old app)
- The settings table view with the needed cells:
1. for settings that show the selected value on one side
2. for settings that have a switch
3. For settings that just open other views (like Help)
4. Sign out
- For type 1 and 2 cells values should come from the state.

(Tapping on a cell does nothing for now)

[iOS Designs page.](https://toggl.invisionapp.com/d/main?origin=v7#/projects/prototypes/19800511) [Android Designs page.](https://toggl.invisionapp.com/d/main?origin=v7#/projects/prototypes/19932960) [Notion page.](https://www.notion.so/toggl/Settings)

## Dependencies
None
## Definition of done
- [ ] Add settings button to calendar tab (or make an issues if not possible) (check designs for correct positioning)
- [ ] Add settings button to log view (check designs for correct positioning)
- [ ] Chose a logic for the structuring of the settings internally that can be used to populate the table view
- [ ] Add the tableview and the cells

**Comment by semanticer** [comment]
So... do I have a final green light [to do this in Compose](https://github.com/toggl/mobile-discussions/issues/73)? @heytherewill

**Comment by heytherewill** [comment]
:doit:
