### ISSUE TITLE
Settings: Implement About

### ISSUE THREAD

**Issue by sofokli1** [toggl/android#525]
## Description
Should include the same options as the old app
- Privacy policy
- Terms of Service
- Licenses

[iOS Designs page.](https://toggl.invisionapp.com/d/main?origin=v7#/projects/prototypes/19800511) [Android Designs page.](https://toggl.invisionapp.com/d/main?origin=v7#/projects/prototypes/19932960) [Notion page.](https://www.notion.so/toggl/Settings)

## Dependencies
`Settings: Add settings view` #512
## Definition of done
- [ ] Implement the logic
- [ ] implement the UI

**Comment by heytherewill** [comment]
Isn't this already done?

**Comment by sofokli1** [comment]
so it seems. @semanticer are you doing anything here?

**Comment by semanticer** [comment]
No, it should be done 🤷‍♂️
