### ISSUE TITLE
Create the .reportLoaded action

### ISSUE THREAD

**Issue by dshr** [toggl/android#561]
## What needs to be done?
- [x] Create the `.reportLoaded` action with `DateRangeSelection`, `ReportTotals` and `ReportSummary` parameters
- [ ] This action should emit a `ReportsSuccess` analytics event
- [x] This action set the `ReportTotals` and `ReportSummary` loadables to `.loaded`
- [x] Add appropriate tests
- [x] Update the [docs](https://www.notion.so/toggl/Reports-54cac91332aa481db6b1de0d3b90aeb9)

### Dependencies
Depends on #554 and #558

**Comment by heytherewill** [comment]
Why two separate loadables? The whole page depends on both and a single effect emits both, so it's more reasonable to bundle both results in a single loadable property
