### ISSUE TITLE
Create the .openDateRangePickerButtonTapped, .dateRangePickerCloseButtonTapped and .dateRangePickerAcceptButtonTapped actions

### ISSUE THREAD

**Issue by dshr** [toggl/android#567]
## What needs to be done?
- [x] The `.openDateRangePickerButtonTapped` should initialise a new `selection` with the current start/end date
- [x] The `.dateRangePickerCloseButtonTapped` should emit a `.dateRangeSelected` action with an appropriate `DateRangeSelection`
- [x] The `.dateRangePickerAcceptButtonTapped` should only set the `selection` to nil
- [ ] Add appropriate tests
- [ ] Update the [docs](https://www.notion.so/toggl/Reports-54cac91332aa481db6b1de0d3b90aeb9)

### Dependencies
Depends on #564

**Comment by heytherewill** [comment]
Did you invert the values of accept and close?
