### ISSUE TITLE
Handle SignUp API interaction (SignUserUpEffect)

### ISSUE THREAD

**Issue by pdrj** [toggl/android#634]
## Description
Implement the SignUp API call. Handle errors correctly. Check the Xamarin app to get the list of possible errors.

## Dependencies
#631 
## Definition of done
SignUpUserEffect is added and it calls the SignUp API, then sets User or Error
Responses are handled properly (go to the main view if signup succeeded or display the appropriate error)
UI is wired up

- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
It's better to work on this after #676 is merged and the api exceptions and handy error handling interceptors are added.
