### ISSUE TITLE
Implement Cancel action

### ISSUE THREAD

**Issue by pdrj** [toggl/android#637]
## Description
Implement Cancel action in SignUp and Login screens
## Dependencies
#631 
## Definition of done
Actions are added
Tests are added
UI is wired up
Action is reduced so that the user is navigated back to the onboarding screen

- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
Hey @pdrj do we even have a cancel action in the sign up/ login screens?

**Comment by pdrj** [comment]
Hm yeah, we've got something like this in the designs:
<img width="381" alt="Screenshot 2020-07-29 at 09 15 36" src="https://user-images.githubusercontent.com/53510080/88768994-27141980-d17c-11ea-8cd5-3006ba792c5d.png">

**Comment by pdrj** [comment]
Ah I see we went full screen on Android - then this action should not be there. Or we should make the screen a modal instead 😆

**Comment by daividssilverio** [comment]
🤔 Are we doing this or not? It looks like we don't have designs yet :/

**Comment by pdrj** [comment]
Let's put this on hold until we get designs. I've started a discussion here sometime back: https://toggl.slack.com/archives/CUHSVKLUV/p1596013821008900

**Comment by pdrj** [comment]
We have the designs and there's no cancel button anymore. Closing this then.
