### ISSUE TITLE
Add a Room DAO for projects

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#65]
## Description
You know the DAO we have for the time entries? Let's create one for projects as well! We will basically need the same methods in the DAO. No need to change the repository layer just yet. Also, no need to have a migration set up; we can just reinstall for now.

## Definition of done
- [ ] A Room DAO for the Project entity is added to the database
- [ ] A proper 1:1 relationship between Time entries and projects is created in the database

**Comment by semanticer** [comment]
@heytherewill You probably meant 1:N right? One project can be referenced in multiple time entries.

**Comment by heytherewill** [comment]
That's what I meant, yes :see_no_evil:
