### ISSUE TITLE
Implement effect batching

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#69]
## Description
In order to avoid rapid firing events from clogging up the UI, we need to give actions the ability to return an array of effects that can be partially applied and only emit the actual UI event once.

## Definition of done
- [ ] Reducers return a list of effects rather than a single effect
- [ ] These returned effects get applied all at once to the main state 
- [ ] They do get applied partially in some intermediate state, so state consistency is achieved
- [ ] The dispatch method can take a list of actions rather than a single action

**Comment by Odrakir** [comment]
For simplicity, in iOS we kept the dispatch method as it is and added another batch method. Dispatch just takes the action, wraps it into an array and calls batch.
