### ISSUE TITLE
Make DatabaseUser properties syncable

### ISSUE THREAD

**Issue by semanticer** [toggl/android#714]
## Description
Refactor all DatabaseUser properties to `*SyncProperty` types with the exception of `Id`, `apiToken` and `serverId`

## Dependencies
#672  

## Definition of done
- [ ] Refactor all properties to corresponding `*SyncProperty` variants.
- [ ] Update all converter extension methods and make sure our domain models stay the same and are using "current" variant of `SyncProperty`

**Comment by simonrozsival** [comment]
I'm not sure if this is a good idea similarly to #715 and also because of #716. The _User_ object has two syncable properties: the default workspace and the beginning of the week setting. If these are part of the Preferences object, then we shouldn't include them in the `DatabaseUser` properties.
