### ISSUE TITLE
Make DatabaseWorkspace properties syncable

### ISSUE THREAD

**Issue by semanticer** [toggl/android#715]
## Description
Refactor `name` DatabaseWorkspace property to `StringSyncProperty` type

## Dependencies
#672  

## Definition of done
- [ ] Refactor `name` DatabaseWorkspace property to `StringSyncProperty` type
- [ ] Update all converter extension methods and make sure our domain models stay the same and are using "current" variant of `SyncProperty`

**Comment by simonrozsival** [comment]
You can't actually change the workspace name in the app. It might not be necessary to have the `name` field as syncable. Currently you can only _create a new workspace_ when you don't have any workspaces at all and you tap the "Create a workspace" button.

**Comment by heytherewill** [comment]
I think we can implement this property just for future-proofness sake
