### ISSUE TITLE
AccesableDatabaseTimeEntry view

### ISSUE THREAD

**Issue by semanticer** [toggl/android#778]
## Description
We need to make sure we are accessing only Time Entries that are "accessible" outside of the sync logic (UI).
Accessible means that `isDeleted = false` and that the referenced workspace is also not deleted. 
The best way to implement this is probably to create an [database view ](https://developer.android.com/training/data-storage/room/creating-views) called something like AccesableDatabaseTimeEntry and TimeEntryDao should then mostly use this view instead of the real table. Alternatively, we could just put this join in every relevant query we make without using the view.

Here is the example how the `@DatabaseView` solution could look like:

```kotlin
@DatabaseView("SELECT * FROM time_entries AS te INNER JOIN workspaces AS w ON te.workspaceId_current = w.id" +
    "WHERE te.is_deleted = 0 AND w.is_deleted = 0")
data class AccesableDatabaseTimeEntry(
    val id: Long = 0,
    val serverId: Long?,
    @Embedded(prefix = "description_")
    val description: StringSyncProperty,
    @Embedded(prefix = "startTime_")
    val startTime: OffsetDateTimeSyncProperty,
    @Embedded(prefix = "duration_")
    val duration: NullableDurationSyncProperty,
    @Embedded(prefix = "billable_")
    val billable: BooleanSyncProperty,
    @Embedded(prefix = "workspaceId_")
    val workspaceId: LongSyncProperty,
    @Embedded(prefix = "projectId_")
    val projectId: NullableLongSyncProperty,
    @Embedded(prefix = "taskId_")
    val taskId: NullableLongSyncProperty,
    @Embedded(prefix = "isDeleted_")
    val isDeleted: BooleanSyncProperty
)
```

Or just take the join and use it in every single query

## Dependencies
None

## Definition of done
Either
- [ ] `AccesableDatabaseTimeEntry` database view is created
- [ ] The view is used in TimeEntryDao and the rest of the related code is fixed
or 
- [ ] All relevant queries in TimeEntryDao are enhanced with join to workspaces and filtered by deleted workspace

**Comment by simonrozsival** [comment]
Superseded by #807
