### ISSUE TITLE
AccesableDatabaseClient view

### ISSUE THREAD

**Issue by semanticer** [toggl/android#780]
## Description
We need to make sure we are accessing only Clients that are "accessible" outside of the sync logic (UI).
Accessible means that `isDeleted = false` and that the referenced workspace is also not deleted. 
The best way to implement this is probably to create an [database view](https://developer.android.com/training/data-storage/room/creating-views) called something like AccesableDatabaseClient and ClientDao should then mostly use this view instead of the real table. Alternatively, we could just put this join in every relevant query we make without using the view.

I gave an example of databaseView solution in #778

## Dependencies
None

## Definition of done
Either
- [x] `AccesableDatabaseClient` database view is created
- [x] The view is used in ClientDao and the rest of the related code is fixed
or 
- [x] All relevant queries in ClientDao are enhanced with join to workspaces and filtered by deleted workspace

**Comment by simonrozsival** [comment]
Superseded by #807
