### ISSUE TITLE
AccesableDatabaseProject view

### ISSUE THREAD

**Issue by semanticer** [toggl/android#781]
## Description
We need to make sure we are accessing only Projects that are "accessible" outside of the sync logic (UI).
Accessible means that `isDeleted = false` and that the referenced workspace is also not deleted. 
The best way to implement this is probably to create an [database view](https://developer.android.com/training/data-storage/room/creating-views) called something like AccesableDatabaseProject and ProjectDao should then mostly use this view instead of the real table. Alternatively, we could just put this join in every relevant query we make without using the view.

I gave an example of databaseView solution in #778

## Dependencies
None

## Definition of done
Either
- [ ] `AccesableDatabaseProject` database view is created
- [ ] The view is used in ProjectDao and the rest of the related code is fixed
or 
- [ ] All relevant queries in ProjectDao are enhanced with join to workspaces and filtered by deleted workspace

**Comment by simonrozsival** [comment]
Superseded by #807
