### ISSUE TITLE
Setup firebase performance

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#8]
## Description
We removed firebase performance from the previous app simply because the Xamarin package was a mess. We can safely include it here now <3

## Definition of done
- [ ] The firebase performance packages are added to the project
- [ ] Firebase performance is setup and hooked to our apps on startup
- [ ] ❓ Data is sent to firebase? pinging @amulware here for clarification, since we might want to only configure that later, when we are using `com.toggl.giskard` rather than just `com.toggl`

**Comment by daividssilverio** [comment]
So, I'd avoid doing this issue until #26 is merged. Since the mentioned PR is adding the Firebase setup as well. Once merged, this issue will be a matter of adding the new dependency and hooking up the app start.
