### ISSUE TITLE
Add correct icon for sync notification

### ISSUE THREAD

**Issue by semanticer** [toggl/android#844]
## Description
The icon we now use in "sync in progress" notification is completely random. We need a real one. We could simply use the standard [material sync icon](https://material.io/resources/icons/?icon=cached&style=baseline) but this needs to be decided in cooperation with designers - maybe they can think of something more uniquely Toggl.

The current provisional implementation looks like this:

**Status bar:**

<img width="413" alt="Screen Shot 2020-09-11 at 12 34 59" src="https://user-images.githubusercontent.com/535613/92913891-7318d600-f42b-11ea-82b6-b282575aab4f.png">

**Expanded notification:**

<img width="413" alt="Screen Shot 2020-09-11 at 12 34 59" src="https://user-images.githubusercontent.com/535613/92913911-79a74d80-f42b-11ea-86ba-40b73357c5f9.png">

## Dependencies
None

## Definition of done
- [x] The new icon now displayed in sync notification

**Comment by milaads** [comment]
@semanticer The standard material sync icon sounds good for now until we have a little bit more time to focus on it.
