### ISSUE TITLE
Add Discard changes dialog when exiting TE editing without saving changes or starting a TE

### ISSUE THREAD

**Issue by pdrj** [toggl/android#887]
## Description
Add Discard changes dialog when exiting TE editing without saving changes or starting a TE

https://toggl.invisionapp.com/console/%5BAndroid%5D-Rebranding-ckem8stapzb0o01wrr0c27nd1/ckeriu1sh02b001xkgurwblmv/play

## Definition of done

- [ ] when exiting TE editing without saving changes or starting a TE, the dialog is shown and the options work as expected

- [ ] The documentation is updated to reflect the changes done in this PR

**Comment by daividssilverio** [comment]
I think this is a duplicate of #868

**Comment by pdrj** [comment]
You're right. Thanks 👍
