### ISSUE TITLE
Setup telemetry services

### ISSUE THREAD

**Issue by heytherewill** [toggl/android#9]
## Description
We need to setup our telemetry services to emit events. This should be a reducer of its own.
We must use both AppCenter and Firebase. The approach is simple: we should have some injectable analytics service with a `track(event: Event)` method. This service will be a composite of two implementations (one for AppCenter and one for Firebase). Every app action must implement an `asEvent` extension method. Then we will have an `AnalyticsReducer` that takes the `analyticsService` as a dependency and handles all app actions to send events over the internet 🛰 

## Definition of done
- [x] The firebase and crashlytics telemetry packages are added to the project
- [ ] All existing actions implement an `asEvent` extension method
- [ ] **All implementations of `asEvent` make sure the events are anonymous and that no user info is being sent to neither telemetry service**
- [ ] The `AnalyticsReducer` is setup and working

**Comment by daividssilverio** [comment]
why both `AppCenter` and `Firebase` tho?
