### ISSUE TITLE
Add AccessRestrictionReducer

### ISSUE THREAD

**Issue by semanticer** [toggl/android#901]
## Description
`AccessRestrictionReducer` should be implemented as a higher-order reducer. For now, it shouldn't do anything, just pass along all the actions it receives.

 ~`AccessRestrictionState` should be added too~

[Notion docs](https://www.notion.so/toggl/Access-Restriction-handling-92338df62076457da8120dd79e989eb8)

## Dependencies
None

## Definition of done
 ~`AccessRestrictionState` is added to global state~
- [ ] `AccessRestrictionReducer` is added as one of the higer order reducers

**Comment by heytherewill** [comment]
How will it be a higher order reducer if it has its own state? 🤔 
Shouldn't it just use the global state instead?

**Comment by semanticer** [comment]
You're right. I don't know what I was thinking.
